[build]
publish = "build/"
command = "CI='' npm run build"

## Yarn 3 cache does not work out of the box as of Jan 2022. Context:
## https://github.com/netlify/build/issues/1535#issuecomment-1021947989
## [build.environment]
## NETLIFY_USE_YARN = "true"
## YARN_VERSION = "3.2.1"
## YARN_FLAGS = "--check-cache"
## YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"
## YARN_ENABLE_GLOBAL_CACHE = "true"
## YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"

[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--legacy-peer-deps"
## YARN_VERSION = "3.2.1"
## YARN_FLAGS = "--mode=update-lockfile"
## YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"

## [[plugins]]
## package = "/.netlify/netlify-plugin-yarn"

[[redirects]]
from = "/api/*"
to = "https://a750-2401-4900-607a-f18d-4fa8-1a95-69f4-c8fb.in.ngrok.io/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
