[build]
publish = "build/"
command = "CI='' yarn run build"

## Yarn 3 cache does not work out of the box as of Jan 2022. Context:
## https://github.com/netlify/build/issues/1535#issuecomment-1021947989
## [build.environment]
## NETLIFY_USE_YARN = "true"
## YARN_VERSION = "3.2.1"
## YARN_FLAGS = "--check-cache"
## YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"
## YARN_ENABLE_GLOBAL_CACHE = "true"
## YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"

## [build.environment]
## NODE_VERSION = "16"
## YARN_VERSION = "3.2.1"
## NPM_FLAGS = "--version"

[build.environment]
NODE_VERSION = "16"
YARN_VERSION = "3.2.1"
YARN_FLAGS = "--mode=update-lockfile"
YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"

[[plugins]]
package = "/.netlify/netlify-plugin-yarn"

[[redirects]]
from = "/api/*"
to = "http://165.232.184.165:9000/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
