version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/care # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - add_ssh_keys:
          fingerprints:
            - "7b:31:e5:d0:a8:97:2a:e1:b5:09:07:6f:77:6f:e5:72"
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: build
          command: npm run build
      - run:
          name: list
          command: ls -lah
      - run:
          name: Deploy
          command: |
            
            sudo apt-get update && sudo apt-get install rsync -y

            echo "The branch is: $CIRCLE_BRANCH"
            if [[ $CIRCLE_BRANCH = "master" ]]
            then
              echo "Syncing to production"
              ssh-keyscan -H 3.7.60.240 >> ~/.ssh/known_hosts
              rsync -avz --delete dist/ deploy@3.7.60.240:/opt/care_prod/
            elif [[ $CIRCLE_BRANCH = "develop" ]]
            then
              echo "Syncing to dev"
              ssh-keyscan -H 3.7.60.169 >> ~/.ssh/known_hosts
              rsync -avz --delete dist/ deploy@3.7.60.169:/opt/care/
            else
              echo "Not Syncing the branch $CIRCLE_BRANCH"
            fi

            # tar -czf build.tar.gz dist/
            # scp build.tar.gz netlify@34.93.26.100:/home/netlify/releases/
            # ssh netlify@34.93.26.100 "cd /home/netlify/releases/; tar xf build.tar.gz; cp -rf /opt/care_fe/ /opt/care_fe.old; mv dist /opt/care_fe/"

